version: '2'
services:
  db:
    image: postgres

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/companies_rest
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env